/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: b4ba775fbdf092e026d4e51ff17ab683)
interface __BaseEnv_Env {
  DB: D1Database;
  AUTH_RATE_LIMITER: RateLimit;
  ASSETS: Fetcher;
  GOOGLE_APP_ORIGIN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'GOOGLE_APP_ORIGIN'>> {}
}
