/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 2a76de73edf48c8c3acc50967d7b9736)
interface __BaseEnv_Env {
  DB: D1Database;
  AUTH_RATE_LIMITER: RateLimit;
  ASSETS: Fetcher;
  GOOGLE_APP_ORIGIN: string;
  CALENDAR_SYNC: DurableObjectNamespace<import('./worker/index').CalendarSync>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index');
    durableNamespaces: 'CalendarSync';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'GOOGLE_APP_ORIGIN'>> {}
}
